


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anna
 */
public class Analytics extends javax.swing.JFrame {
    static User user;

    /**
     * Creates new form analytics
     */
    public Analytics(User user) {
        initComponents();
        this.user = user;
        new DatabaseAccess().getAnalytics(user.getUserID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAnalytics = new javax.swing.JLabel();
        lblEL = new javax.swing.JLabel();
        lblELQA = new javax.swing.JLabel();
        lblDF = new javax.swing.JLabel();
        lblCI = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblES = new javax.swing.JLabel();
        lblOZ = new javax.swing.JLabel();
        lblWM = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblELQAval = new javax.swing.JLabel();
        lblELPA = new javax.swing.JLabel();
        lblELPAval = new javax.swing.JLabel();
        lblESQA = new javax.swing.JLabel();
        lblESQAval = new javax.swing.JLabel();
        lblESPA = new javax.swing.JLabel();
        lblESPAval = new javax.swing.JLabel();
        lblDFQA = new javax.swing.JLabel();
        lblDFQAval = new javax.swing.JLabel();
        lblDFPA = new javax.swing.JLabel();
        lblDFPAval = new javax.swing.JLabel();
        lblOZQA = new javax.swing.JLabel();
        lblOZQAval = new javax.swing.JLabel();
        lblOZPA = new javax.swing.JLabel();
        lblOZPAval = new javax.swing.JLabel();
        lblWMQA = new javax.swing.JLabel();
        lblWMQAval = new javax.swing.JLabel();
        lblWMPA = new javax.swing.JLabel();
        lblWMPAval = new javax.swing.JLabel();
        lblCIQA = new javax.swing.JLabel();
        lblCIQAval = new javax.swing.JLabel();
        lblCIPA = new javax.swing.JLabel();
        lblCIPAval = new javax.swing.JLabel();
        lblPLQA = new javax.swing.JLabel();
        lblPLQAval = new javax.swing.JLabel();
        lblPLPA = new javax.swing.JLabel();
        lblPLPAval = new javax.swing.JLabel();
        lblOQA = new javax.swing.JLabel();
        lblOQAval = new javax.swing.JLabel();
        lblOPA = new javax.swing.JLabel();
        lblOPAval = new javax.swing.JLabel();
        lblDMQA = new javax.swing.JLabel();
        lblDMQAval = new javax.swing.JLabel();
        lblDMPA = new javax.swing.JLabel();
        lblDMPAval = new javax.swing.JLabel();
        lblCDQA = new javax.swing.JLabel();
        lblCDQAval = new javax.swing.JLabel();
        lblCDPA = new javax.swing.JLabel();
        lblCDPAval = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(113, 141, 206));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        lblAnalytics.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnalytics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnalytics.setText("Analytics");

        lblEL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEL.setText("Elements of Life (EL)");

        lblELQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblELQA.setText("Questions Attempted:");

        lblDF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDF.setText("Developing Fuels (DF)");

        lblCI.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCI.setText("The Chemical Industry (CI)");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Polymers and Life (PL)");

        lblES.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblES.setText("Elements of the Sea (ES)");

        lblOZ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblOZ.setText("The Ozone Story (OZ)");

        lblWM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblWM.setText("What's in a Medicine? (WM)");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Oceans (O)");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Developing Metals (DM)");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Colour by Design (CD)");

        lblELQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblELQAval.setText("0");

        lblELPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblELPA.setText("% Accuracy:");

        lblELPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblELPAval.setText("0");

        lblESQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblESQA.setText("Questions Attempted:");

        lblESQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblESQAval.setText("jLabel22");

        lblESPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblESPA.setText("% Accuracy:");

        lblESPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblESPAval.setText("jLabel24");

        lblDFQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDFQA.setText("Questions Attempted:");

        lblDFQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDFQAval.setText("0");

        lblDFPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDFPA.setText("% Accuracy:");

        lblDFPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDFPAval.setText("0");

        lblOZQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOZQA.setText("Questions Attempted:");

        lblOZQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOZQAval.setText("jLabel22");

        lblOZPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOZPA.setText("% Accuracy:");

        lblOZPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOZPAval.setText("jLabel24");

        lblWMQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblWMQA.setText("Questions Attempted:");

        lblWMQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblWMQAval.setText("jLabel22");

        lblWMPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblWMPA.setText("% Accuracy:");

        lblWMPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblWMPAval.setText("jLabel24");

        lblCIQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCIQA.setText("Questions Attempted:");

        lblCIQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCIQAval.setText("jLabel22");

        lblCIPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCIPA.setText("% Accuracy:");

        lblCIPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCIPAval.setText("jLabel24");

        lblPLQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPLQA.setText("Questions Attempted:");

        lblPLQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPLQAval.setText("jLabel22");

        lblPLPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPLPA.setText("% Accuracy:");

        lblPLPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPLPAval.setText("jLabel24");

        lblOQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOQA.setText("Questions Attempted:");

        lblOQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOQAval.setText("jLabel22");

        lblOPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOPA.setText("% Accuracy:");

        lblOPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOPAval.setText("jLabel24");

        lblDMQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDMQA.setText("Questions Attempted:");

        lblDMQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDMQAval.setText("jLabel22");

        lblDMPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDMPA.setText("% Accuracy:");

        lblDMPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDMPAval.setText("jLabel24");

        lblCDQA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCDQA.setText("Questions Attempted:");

        lblCDQAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCDQAval.setText("jLabel22");

        lblCDPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCDPA.setText("% Accuracy:");

        lblCDPAval.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCDPAval.setText("jLabel24");

        btnBack.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblWM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(lblOZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblELQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblELQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblELPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblELPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDFQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDFQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDFPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDFPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblESQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblESQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblESPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblESPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOZQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOZQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOZPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOZPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWMQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWMQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblWMPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWMPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCI, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCIQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCIQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCIPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCIPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPLQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPLQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPLPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPLPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDMQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDMQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDMPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDMPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCDQA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCDQAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCDPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCDPAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAnalytics)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEL)
                    .addComponent(lblCI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblELQA)
                    .addComponent(lblELQAval)
                    .addComponent(lblELPA)
                    .addComponent(lblELPAval)
                    .addComponent(lblCIQA)
                    .addComponent(lblCIQAval)
                    .addComponent(lblCIPA)
                    .addComponent(lblCIPAval))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDF)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDFQA)
                    .addComponent(lblDFQAval)
                    .addComponent(lblDFPA)
                    .addComponent(lblDFPAval)
                    .addComponent(lblPLQA)
                    .addComponent(lblPLQAval)
                    .addComponent(lblPLPA)
                    .addComponent(lblPLPAval))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblES)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblESQA)
                    .addComponent(lblESQAval)
                    .addComponent(lblESPA)
                    .addComponent(lblESPAval)
                    .addComponent(lblOQA)
                    .addComponent(lblOQAval)
                    .addComponent(lblOPA)
                    .addComponent(lblOPAval))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOZ)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOZQA)
                    .addComponent(lblOZQAval)
                    .addComponent(lblOZPA)
                    .addComponent(lblOZPAval)
                    .addComponent(lblDMQA)
                    .addComponent(lblDMQAval)
                    .addComponent(lblDMPA)
                    .addComponent(lblDMPAval))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWM)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWMQA)
                    .addComponent(lblWMQAval)
                    .addComponent(lblWMPA)
                    .addComponent(lblWMPAval)
                    .addComponent(lblCDQA)
                    .addComponent(lblCDQAval)
                    .addComponent(lblCDPA)
                    .addComponent(lblCDPAval))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AccountHome(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analytics(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnalytics;
    private javax.swing.JLabel lblCDPA;
    private javax.swing.JLabel lblCDPAval;
    private javax.swing.JLabel lblCDQA;
    private javax.swing.JLabel lblCDQAval;
    private javax.swing.JLabel lblCI;
    private javax.swing.JLabel lblCIPA;
    private javax.swing.JLabel lblCIPAval;
    private javax.swing.JLabel lblCIQA;
    private javax.swing.JLabel lblCIQAval;
    private javax.swing.JLabel lblDF;
    private javax.swing.JLabel lblDFPA;
    private javax.swing.JLabel lblDFPAval;
    private javax.swing.JLabel lblDFQA;
    private javax.swing.JLabel lblDFQAval;
    private javax.swing.JLabel lblDMPA;
    private javax.swing.JLabel lblDMPAval;
    private javax.swing.JLabel lblDMQA;
    private javax.swing.JLabel lblDMQAval;
    private javax.swing.JLabel lblEL;
    private javax.swing.JLabel lblELPA;
    private javax.swing.JLabel lblELPAval;
    private javax.swing.JLabel lblELQA;
    private javax.swing.JLabel lblELQAval;
    private javax.swing.JLabel lblES;
    private javax.swing.JLabel lblESPA;
    private javax.swing.JLabel lblESPAval;
    private javax.swing.JLabel lblESQA;
    private javax.swing.JLabel lblESQAval;
    private javax.swing.JLabel lblOPA;
    private javax.swing.JLabel lblOPAval;
    private javax.swing.JLabel lblOQA;
    private javax.swing.JLabel lblOQAval;
    private javax.swing.JLabel lblOZ;
    private javax.swing.JLabel lblOZPA;
    private javax.swing.JLabel lblOZPAval;
    private javax.swing.JLabel lblOZQA;
    private javax.swing.JLabel lblOZQAval;
    private javax.swing.JLabel lblPLPA;
    private javax.swing.JLabel lblPLPAval;
    private javax.swing.JLabel lblPLQA;
    private javax.swing.JLabel lblPLQAval;
    private javax.swing.JLabel lblWM;
    private javax.swing.JLabel lblWMPA;
    private javax.swing.JLabel lblWMPAval;
    private javax.swing.JLabel lblWMQA;
    private javax.swing.JLabel lblWMQAval;
    // End of variables declaration//GEN-END:variables
}
