/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anna
 */
public class Calculations extends javax.swing.JFrame {

    /**
     * Creates new form Calculations
     */
    public Calculations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVal1 = new javax.swing.JLabel();
        cbVal1 = new javax.swing.JComboBox<>();
        tfVal1 = new javax.swing.JTextField();
        lblVal2 = new javax.swing.JLabel();
        cbVal2 = new javax.swing.JComboBox<>();
        tfVal2 = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        lblUnits = new javax.swing.JLabel();
        lblExplanation = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblResultResult = new javax.swing.JLabel();
        lblExplanationText = new javax.swing.JLabel();
        lblValue3 = new javax.swing.JLabel();
        lblValue4 = new javax.swing.JLabel();
        lblValue5 = new javax.swing.JLabel();
        lblValue6 = new javax.swing.JLabel();
        cbVal3 = new javax.swing.JComboBox<>();
        cbVal4 = new javax.swing.JComboBox<>();
        cbVal5 = new javax.swing.JComboBox<>();
        cbVal6 = new javax.swing.JComboBox<>();
        tfVal3 = new javax.swing.JTextField();
        tfVal4 = new javax.swing.JTextField();
        tfVal5 = new javax.swing.JTextField();
        tfVal6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(113, 141, 206));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        lblVal1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVal1.setText("Value 1:");

        cbVal1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVal1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-None selected-", "Density/ g dm^-3", "Energy/ J", "Enthalpy change/ J mol^-1", "Frequency/ Hz", "Mass/ g", "Moles", "Mr", "Pressure/ Pa", "Specific heat capacity/J g^-1 K^-1", "Temperature/ K", "Volume/dm^3", "Wavelength/ m" }));
        cbVal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVal1ActionPerformed(evt);
            }
        });

        tfVal1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblVal2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVal2.setText("Value 2:");

        cbVal2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVal2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-None selected-", "Density/ g dm^-3", "Energy/ J", "Enthalpy change/ J mol^-1", "Frequency/ Hz", "Mass/ g", "Moles", "Mr", "Pressure/ Pa", "Specific heat capacity/J g^-1 K^-1", "Temperature/ K", "Volume/dm^3", "Wavelength/ m" }));

        tfVal2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblResult.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblResult.setText("Result:");

        lblUnits.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUnits.setText("<units>");

        lblExplanation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblExplanation.setText("Explanation:");

        btnBack.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblResultResult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblResultResult.setText("<result>");

        lblExplanationText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblExplanationText.setText("<explanation>");

        lblValue3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValue3.setText("Value 3:");

        lblValue4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValue4.setText("Value 4:");

        lblValue5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValue5.setText("Value 5:");

        lblValue6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValue6.setText("Value 6:");

        cbVal3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVal3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-None selected-", "Density/ g dm^-3", "Energy/ J", "Enthalpy change/ J mol^-1", "Frequency/ Hz", "Mass/ g", "Moles", "Mr", "Pressure/ Pa", "Specific heat capacity/J g^-1 K^-1", "Temperature/ K", "Volume/dm^3", "Wavelength/ m" }));

        cbVal4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVal4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-None selected-", "Density/ g dm^-3", "Energy/ J", "Enthalpy change/ J mol^-1", "Frequency/ Hz", "Mass/ g", "Moles", "Mr", "Pressure/ Pa", "Specific heat capacity/J g^-1 K^-1", "Temperature/ K", "Volume/dm^3", "Wavelength/ m" }));

        cbVal5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVal5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-None selected-", "Density/ g dm^-3", "Energy/ J", "Enthalpy change/ J mol^-1", "Frequency/ Hz", "Mass/ g", "Moles", "Mr", "Pressure/ Pa", "Specific heat capacity/J g^-1 K^-1", "Temperature/ K", "Volume/dm^3", "Wavelength/ m" }));

        cbVal6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVal6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-None selected-", "Density/ g dm^-3", "Energy/ J", "Enthalpy change/ J mol^-1", "Frequency/ Hz", "Mass/ g", "Moles", "Mr", "Pressure/ Pa", "Specific heat capacity/J g^-1 K^-1", "Temperature/ K", "Volume/dm^3", "Wavelength/ m" }));

        tfVal3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tfVal4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tfVal5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tfVal6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Select your values and type their numbers");

        btnCalculate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValue3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfVal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValue4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfVal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValue5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfVal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValue6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfVal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblVal2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbVal2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblVal1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfVal2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblExplanation))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCalculate)
                                        .addGap(102, 102, 102))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblResult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblResultResult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addComponent(lblExplanationText))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblVal1, lblVal2, lblValue3, lblValue4, lblValue5, lblValue6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbVal1, cbVal2, cbVal3, cbVal4, cbVal5, cbVal6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfVal1, tfVal2, tfVal3, tfVal4, tfVal5, tfVal6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVal1)
                    .addComponent(cbVal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVal2)
                    .addComponent(cbVal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue3)
                    .addComponent(cbVal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue4)
                    .addComponent(cbVal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue5)
                    .addComponent(cbVal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue6)
                    .addComponent(cbVal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult)
                    .addComponent(lblResultResult)
                    .addComponent(lblUnits))
                .addGap(15, 15, 15)
                .addComponent(lblExplanation)
                .addGap(30, 30, 30)
                .addComponent(lblExplanationText)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new CalcsOrPeriod().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        String value1 = String.valueOf(cbVal1.getSelectedItem());
        String value2 = String.valueOf(cbVal2.getSelectedItem());
        if(value1.contains("/")){
            String[] parts = value1.split("/");
            value1 = parts[0];
        }
        if(value2.contains("/")){
            String[] parts = value2.split("/");
            value2 = parts[0];
        }
        String[] values = {value1, value2};
        new DatabaseAccess().getEquation(values);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void cbVal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cbVal1;
    private javax.swing.JComboBox<String> cbVal2;
    private javax.swing.JComboBox<String> cbVal3;
    private javax.swing.JComboBox<String> cbVal4;
    private javax.swing.JComboBox<String> cbVal5;
    private javax.swing.JComboBox<String> cbVal6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExplanation;
    private javax.swing.JLabel lblExplanationText;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResultResult;
    private javax.swing.JLabel lblUnits;
    private javax.swing.JLabel lblVal1;
    private javax.swing.JLabel lblVal2;
    private javax.swing.JLabel lblValue3;
    private javax.swing.JLabel lblValue4;
    private javax.swing.JLabel lblValue5;
    private javax.swing.JLabel lblValue6;
    private javax.swing.JTextField tfVal1;
    private javax.swing.JTextField tfVal2;
    private javax.swing.JTextField tfVal3;
    private javax.swing.JTextField tfVal4;
    private javax.swing.JTextField tfVal5;
    private javax.swing.JTextField tfVal6;
    // End of variables declaration//GEN-END:variables
}
