/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anna
 */
public class Periodicity extends javax.swing.JFrame {
    static User user;

    /**
     * Creates new form Periodicity
     */
    public Periodicity(User user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGroup = new javax.swing.JLabel();
        cbGroup = new javax.swing.JComboBox<>();
        lblIon = new javax.swing.JLabel();
        cbIon = new javax.swing.JComboBox<>();
        lblProperty = new javax.swing.JLabel();
        cbProperty = new javax.swing.JComboBox<>();
        lblFormulae = new javax.swing.JLabel();
        lblTrend = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblExplanation = new javax.swing.JLabel();
        lblTrendText = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(113, 141, 206));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        lblGroup.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGroup.setText("Group:");

        cbGroup.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Group 1", "Group 2", "Group 3", "Group 4", "Group 5", "Group 6", "Group 7", "Group 8" }));
        cbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGroupActionPerformed(evt);
            }
        });

        lblIon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIon.setText("Ion:");

        cbIon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbIon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Ion Selected", "OH-", "CO3 2+", "SO4 2-" }));
        cbIon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIonActionPerformed(evt);
            }
        });

        lblProperty.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblProperty.setText("Property:");

        cbProperty.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbProperty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Melting Point", "Boiling Point", "Density", "Electronegativity", "Reactivity", "Solubility" }));

        lblFormulae.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFormulae.setText("How to work out formulae:");

        lblTrend.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTrend.setText("Trend:");

        btnBack.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblExplanation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblExplanation.setText("<explanation>");

        lblTrendText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTrendText.setText("<trend>");

        btnCalculate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalculate.setText("Calculate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExplanation)
                            .addComponent(lblTrendText))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFormulae)
                                    .addComponent(lblTrend)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblGroup, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIon, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblProperty, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbGroup, 0, 235, Short.MAX_VALUE)
                                            .addComponent(cbIon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbProperty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(197, 197, 197)
                                .addComponent(btnCalculate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGroup)
                    .addComponent(cbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIon)
                    .addComponent(cbIon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProperty)
                    .addComponent(cbProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFormulae)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplanation)
                .addGap(60, 60, 60)
                .addComponent(lblTrend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrendText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new CalcsOrPeriod(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbIonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIonActionPerformed
        // TODO add your handling code here:
        String selectedIon = String.valueOf(cbIon.getSelectedItem());
        if (!(selectedIon.equals("No Ion Selected"))&& String.valueOf(cbGroup.getSelectedItem()).equals("Group 8")){
            cbIon.setSelectedItem("No Ion Selected");
            new DialogueBoxGrpAndIon().setVisible(true);
        }
    }//GEN-LAST:event_cbIonActionPerformed

    private void cbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGroupActionPerformed
        // TODO add your handling code here:
        String selectedIon = String.valueOf(cbIon.getSelectedItem());
        if (!(selectedIon.equals("No Ion Selected"))&& String.valueOf(cbGroup.getSelectedItem()).equals("Group 8")){
            cbIon.setSelectedItem("No Ion Selected");
            new DialogueBoxGrpAndIon().setVisible(true);
        }
    }//GEN-LAST:event_cbGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Periodicity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Periodicity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Periodicity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Periodicity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Periodicity(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cbGroup;
    private javax.swing.JComboBox<String> cbIon;
    private javax.swing.JComboBox<String> cbProperty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExplanation;
    private javax.swing.JLabel lblFormulae;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblIon;
    private javax.swing.JLabel lblProperty;
    private javax.swing.JLabel lblTrend;
    private javax.swing.JLabel lblTrendText;
    // End of variables declaration//GEN-END:variables
}
